
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "9090:9090"
    environment:
      - PORT=9090
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=order_service
      - DB_SSLMODE=disable
      - ENV=development
    depends_on:
      - postgres
    volumes:
      - .:/mnt
    command: [ "./scripts/run.sh" ]
  postgres:
    image: postgres:15-alpine
    container_name: order-service-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
